### ISSUE TITLE
mask too narrow 255.255.255.255

### ISSUE THREAD

**Issue by ram-argus** [mitsutaka/docker-libs#1]
I'm using your client to connect to the latest softether server (pc2pc mode)
I'm trying to give it a static IP to a client connected to the server, but get Mask:255.255.255.255 which prevents the client from communicating to the rest of the vpn network

any idea how to fix this?

**Comment by mitsutaka** [comment]
@ram-argus This image uses ip command to set IP address. Can you try to define prefix after IP address like  `````TAP_IPADDR=xxx.xxx.xxx.xxx/xx````` ?

**Comment by ram-argus** [comment]
looks like it works, thanks!

by the way, to run under kubernetes with proper permissions--this is what's needed:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: softether-client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: softether-client
    spec:
      hostNetwork: true
      containers:
      - name: softether-client
        securityContext:
          privileged: true
        image: mitsutaka/softether-vpnclient
        env:
        - name: "VPN_SERVER"
          value: vpn.my-domain.com
        - name: "TAP_IPADDR"
          value: 192.168.30.3/24
        - name: "VIRTUAL_HUB"
          value: myHUB
        - name: "ACCOUNT_USER"
          valueFrom:
            secretKeyRef:
              name: myVpnSecret
              key: username  
        - name: "ACCOUNT_PASS"
            secretKeyRef:
              name: myVpnSecret
              key: password 
```
